/**
 * Mitgelieferte Beispielsequenz (Französisch).
 *
 * Sie ist vollständig ausgefüllt, damit der Unterrichtsmodus ohne
 * Vorbereitungsaufwand erprobt werden kann. Medien sind bewusst nicht
 * enthalten – die App lädt keine Dateien aus dem Netz.
 */
import type { Lexeme, Sequence } from './model';
import { createConceptCheck } from './ccq';
import { createCorpusExample, createCorpusMiniature } from './corpus';
import { createLexeme, createSequence } from './schema';

type LexemeSeed = Partial<Lexeme> & Pick<Lexeme, 'expression' | 'coreMeaning'>;

const SEEDS: LexemeSeed[] = [
  {
    expression: 'Ça te dit de… ?',
    learningGoal: 'productive',
    imageability: 'gering',
    inferenceSuitability: 'bedingt',
    transferRisk: 'mittel',
    confusionGroup: 'Vorschlag und Reaktion',
    coreMeaning: 'Hast du Lust, etwas zu tun?',
    targetExplanation: 'On propose une activité à quelqu’un.',
    targetPrompt: 'Écoutez : qui propose quelque chose ?',
    teacherNote: 'Chunk als Ganzes anbieten; erst nach der Prüfung das Schriftbild zeigen.',
    communicativeFunction: 'einen Vorschlag machen',
    modelUtterance: "Ça te dit d'aller au cinéma samedi ?",
    lexicalType: 'sprechakt',
    semantisationMethod: 'Mini-Dialog mit Reaktion',
    repertoire: 'kern',
    selectionReason:
      'Ohne diesen Chunk kommt das Rollenspiel nicht in Gang – er eröffnet den Vorschlag und wird von den Lernenden selbst gebraucht.',
    connotation: 'umgangssprachlich',
    wordClass: 'wendung',
    elicitingTechniques: ['mimik', 'kontext'],
    elicitingContext:
      'Zwei Freunde, Freitagnachmittag, Handy in der Hand – vorspielen, wie eine Person die andere fragt.',
    wordCue: 'Ça te…',
    keyCollocation: "Ça te dit d'aller au cinéma ?",
    situation: 'Zwei Jugendliche schreiben sich am Freitagnachmittag. Eine Person möchte etwas gemeinsam unternehmen.',
    pronunciationHint: 'Bindung zwischen „Ça“ und „te“ nicht trennen; der Satz steigt am Ende an.',
    prosodyNote: 'Fragemelodie steigend; „de“ wird zu „d’“ vor Vokal.',
    ipa: '[sa tə di də]',
    morphology: 'unveränderlicher Chunk; „te“ nur beim Duzen, sonst „Ça vous dit de… ?“',
    valency: 'Ça te dit de + Infinitiv',
    sentenceFrame: 'Ça te dit de ______ ?',
    collocations: "Ça te dit d'aller… / de venir… / de faire…",
    wordFamily: 'dire – ça me dit – ça ne me dit rien',
    register: 'mündlich, vertraut (Duzen)',
    culturalNote: 'Unter Jugendlichen die übliche Form des Vorschlags; im Brief oder gegenüber Erwachsenen zu informell.',
    example: "Ça te dit de venir avec nous au parc ?",
    nonExample: 'Ça te dit de remplir ce formulaire ? – Ein Vorschlag ohne Freizeitcharakter wirkt seltsam.',
    contrastExample: 'Vous voulez venir avec nous ? – derselbe Zweck, formeller Register.',
    confusionRisk: '„Ça te dit quelque chose ?“ heißt „Sagt dir das etwas?“ – andere Bedeutung.',
    checkTemplateId: 'situation-zu-ausdruck',
    ccqs: [
      createConceptCheck({
        question: 'Est-ce que la personne propose quelque chose ou refuse ?',
        expectedAnswer: 'Elle propose.',
        options: ['Elle propose.', 'Elle refuse.'],
        feature: 'absicht',
        format: 'a-b',
        target: 'use',
        misconception: 'Die Frageform wird als Unsicherheit gedeutet statt als Vorschlag.',
        alternativeClarification: 'Mini-Dialog mit Zustimmung und Ablehnung gegenüberstellen.',
        language: 'fr',
      }),
      createConceptCheck({
        question: 'On dit ça à un ami ou à la directrice ?',
        expectedAnswer: 'À un ami.',
        options: ['À un ami.', 'À la directrice.'],
        feature: 'register',
        format: 'a-b',
        target: 'use',
        misconception: 'Der Chunk wird für jede Situation als höflich genug gehalten.',
        alternativeClarification: '„Ça vous dit de… ?“ danebenstellen.',
        language: 'fr',
      }),
    ],
    translation: 'Hast du Lust, …?',
    simplifiedExplanation: 'Man fragt: Willst du mitmachen?',
    extraHint: 'Chunk als Ganzes lernen, nicht Wort für Wort übersetzen.',
    extensionTask: 'Formuliert denselben Vorschlag höflich mit „Ça vous dit de… ?“.',
    communicativeTask: 'Schlagt eurer Partnerin oder eurem Partner eine Aktivität für Samstag vor.',
  },
  {
    expression: 'Pourquoi pas !',
    learningGoal: 'productive',
    imageability: 'gering',
    inferenceSuitability: 'ungeeignet',
    transferRisk: 'hoch',
    confusionGroup: 'Vorschlag und Reaktion',
    coreMeaning: 'Einverstanden, gute Idee.',
    targetExplanation: 'On accepte la proposition avec plaisir.',
    targetPrompt: 'Écoutez l’intonation.',
    communicativeFunction: 'einem Vorschlag zustimmen',
    modelUtterance: '— Ça te dit d’aller à la piscine ? — Pourquoi pas !',
    lexicalType: 'sprechakt',
    semantisationMethod: 'Mini-Dialog mit Reaktion',
    repertoire: 'kern',
    selectionReason: 'Ohne eine kurze Zustimmung bricht das Rollenspiel nach dem Vorschlag ab.',
    connotation: 'umgangssprachlich',
    wordClass: 'wendung',
    elicitingTechniques: ['mimik', 'kontext'],
    elicitingContext: 'Vorschlag vorspielen und mit Mimik zustimmen – die Wendung folgt als Antwort.',
    wordCue: 'Pour…',
    keyCollocation: '— Ça te dit… ? — Pourquoi pas !',
    situation: 'Auf einen Vorschlag folgt eine freundliche, offene Zustimmung.',
    pronunciationHint: 'Kein Fragezeichen: fallende Melodie, sonst klingt es nach echter Rückfrage.',
    prosodyNote: 'Betonung auf „pas“; fallende Intonation.',
    ipa: '[puʁ.kwa pa]',
    morphology: 'feste Wendung, unveränderlich',
    sentenceFrame: '— Vorschlag — Pourquoi pas !',
    register: 'mündlich, freundlich',
    example: '— On fait du vélo ? — Pourquoi pas !',
    nonExample: 'Pourquoi pas ? mit Fragemelodie ist keine Zustimmung, sondern eine Rückfrage.',
    contrastExample: 'Bonne idée ! – deutlichere Begeisterung.',
    confusionRisk: 'Wörtlich „Warum nicht?“ – im Deutschen klingt das zögernd, im Französischen ist es zustimmend.',
    checkTemplateId: 'reaktion-formulieren',
    ccqs: [
      createConceptCheck({
        question: 'Est-ce que la personne est d’accord ?',
        expectedAnswer: 'Oui.',
        feature: 'absicht',
        format: 'ja-nein',
        target: 'meaning',
        misconception: 'Die wörtliche Lesart „Warum nicht?“ lässt an Zögern denken.',
        alternativeClarification: 'Zustimmung und Rückfrage mit Intonation vorsprechen und vergleichen lassen.',
        language: 'fr',
      }),
      createConceptCheck({
        question: 'Est-ce qu’on dit ça avant ou après une proposition ?',
        expectedAnswer: 'Après.',
        options: ['Avant', 'Après'],
        feature: 'funktion',
        format: 'a-b',
        target: 'use',
        language: 'fr',
      }),
    ],
    translation: 'Warum nicht! / Gerne!',
    extraHint: 'Intonation mitsprechen lassen – sie trägt hier die Bedeutung.',
    communicativeTask: 'Reagiert auf drei Vorschläge eurer Partnerin oder eures Partners.',
  },
  {
    expression: 'Je préfère…',
    learningGoal: 'productive',
    imageability: 'gering',
    inferenceSuitability: 'bedingt',
    transferRisk: 'gering',
    coreMeaning: 'Ich möchte lieber etwas anderes.',
    communicativeFunction: 'eine Präferenz ausdrücken',
    modelUtterance: 'Je préfère faire du skate.',
    lexicalType: 'kollokation',
    semantisationMethod: 'Satzrahmen an der Tafel',
    repertoire: 'kern',
    situation: 'Zwei Vorschläge liegen auf dem Tisch; eine Person wählt einen davon aus.',
    pronunciationHint: 'Offenes è in „préfère“ – anders als in „préférer“.',
    prosodyNote: 'Akzentwechsel: je préfère, aber nous préférons.',
    ipa: '[ʒə pʁe.fɛʁ]',
    morphology: 'préférer, Stammwechsel é → è: je préfère, tu préfères, nous préférons',
    valency: 'préférer + Infinitiv oder + Nomen',
    sentenceFrame: 'Je préfère ______ .',
    collocations: 'je préfère aller… / faire… / rester…',
    wordFamily: 'la préférence – préféré(e)',
    register: 'neutral',
    example: 'Je préfère rester à la maison.',
    nonExample: 'Je préfère que tu viens. – hier wäre der Subjonctif nötig.',
    contrastExample: 'Je veux faire du skate. – Wunsch statt Auswahl.',
    confusionRisk: 'Nicht mit „Je préférerais“ (höflicher Konditional) verwechseln.',
    checkTemplateId: 'ausdruck-auswaehlen',
    ccqs: [
      createConceptCheck({
        question: 'La personne choisit une autre activité ou elle refuse tout ?',
        expectedAnswer: 'Elle choisit une autre activité.',
        options: ['Elle choisit autre chose.', 'Elle refuse tout.'],
        feature: 'kernbedeutung',
        format: 'a-b',
        target: 'meaning',
        misconception: '„préférer“ wird als Ablehnung gelesen.',
        alternativeClarification: 'Zwei Vorschläge nebeneinander und eine Wahl treffen lassen.',
        language: 'fr',
      }),
    ],
    translation: 'Ich mag lieber …',
    multilingualComparison: 'engl. I prefer to … – gleiche Struktur mit Infinitiv.',
    communicativeTask: 'Lehnt einen Vorschlag freundlich ab und nennt eine Alternative.',
  },
  {
    expression: 'aller au cinéma',
    learningGoal: 'productive',
    imageability: 'hoch',
    inferenceSuitability: 'geeignet',
    transferRisk: 'mittel',
    coreMeaning: 'ins Kino gehen',
    communicativeFunction: 'eine Aktivität benennen',
    modelUtterance: 'On peut aller au cinéma dimanche après-midi.',
    lexicalType: 'kollokation',
    semantisationMethod: 'Bausteinmuster mit Varianten',
    repertoire: 'kern',
    selectionReason: 'Die Lernenden brauchen mindestens eine Aktivität, die sie im Rollenspiel vorschlagen können.',
    connotation: 'neutral',
    wordClass: 'wendung',
    elicitingTechniques: ['bild', 'realie'],
    elicitingContext: 'Kinoprogramm oder Eintrittskarte zeigen.',
    wordCue: 'aller au…',
    keyCollocation: 'aller au cinéma',
    targetExplanation: 'On va au cinéma pour voir un film.',
    situation: 'Ein Kinoprogramm hängt aus; die Gruppe überlegt, was sie unternehmen kann.',
    pronunciationHint: 'Liaison: „aller_au“ wird gebunden gesprochen.',
    ipa: '[a.le o si.ne.ma]',
    morphology: 'aller à + le → au; à la piscine, à l’opéra, aux Halles',
    valency: 'aller à + Ort',
    sentenceFrame: 'aller ______ (au / à la / à l’)',
    collocations: 'aller au cinéma, aller au parc, aller à la piscine',
    wordFamily: 'le cinéma – une séance – un film',
    register: 'neutral',
    example: 'Samedi soir, on va au cinéma.',
    nonExample: 'aller à le cinéma – die Verschmelzung fehlt.',
    contrastExample: 'aller à la piscine – gleiches Muster, anderes Genus.',
    confusionRisk: 'Kontraktion au/à la wird häufig übergeneralisiert.',
    checkTemplateId: 'welcher-ausdruck-fehlt',
    translation: 'ins Kino gehen',
    communicativeTask: 'Nennt drei Orte, die ihr am Wochenende besuchen könnt.',
  },
  {
    expression: 'faire du skate',
    learningGoal: 'receptive',
    imageability: 'hoch',
    inferenceSuitability: 'geeignet',
    transferRisk: 'mittel',
    coreMeaning: 'Skateboard fahren',
    communicativeFunction: 'eine Freizeitaktivität benennen',
    modelUtterance: 'Le samedi, je fais du skate au parc.',
    lexicalType: 'handlung',
    semantisationMethod: 'Pantomime durch die Lehrkraft',
    repertoire: 'stuetze',
    situation: 'Im Park üben Jugendliche mit ihren Skateboards.',
    pronunciationHint: '„skate“ wird französisch ausgesprochen: [skɛt].',
    ipa: '[fɛʁ dy skɛt]',
    morphology: 'faire du / de la / de l’ + Sportart',
    valency: 'faire de + Aktivität',
    sentenceFrame: 'faire ______ (du / de la / de l’)',
    collocations: 'faire du vélo, faire de la danse, faire de l’escalade',
    wordFamily: 'un skateur – une planche',
    register: 'mündlich, jugendsprachlich verbreitet',
    example: 'Mon frère fait du skate tous les mercredis.',
    nonExample: 'jouer au skate – im Französischen nur bei Ballspielen: jouer au foot.',
    contrastExample: 'jouer au foot – anderes Muster für Mannschaftssport.',
    confusionRisk: 'faire de vs. jouer à wird oft vertauscht.',
    checkTemplateId: 'situation-zu-ausdruck',
    ccqs: [
      createConceptCheck({
        question: 'On dit « faire du skate » ou « jouer au skate » ?',
        expectedAnswer: 'faire du skate',
        options: ['faire du skate', 'jouer au skate'],
        feature: 'begriffsgrenze',
        format: 'a-b',
        target: 'meaning',
        misconception: '„jouer à“ wird auf alle Sportarten übertragen.',
        alternativeClarification: 'Mit „jouer au foot“ vergleichen und beide Muster gegenüberstellen.',
        language: 'fr',
      }),
    ],
    translation: 'skaten',
    extensionTask: 'Sammelt fünf weitere Aktivitäten mit „faire du / de la“.',
    communicativeTask: 'Erzählt, welche Aktivität ihr am Wochenende macht.',
  },
  {
    expression: 'Je ne peux pas.',
    learningGoal: 'productive',
    imageability: 'gering',
    inferenceSuitability: 'geeignet',
    transferRisk: 'gering',
    confusionGroup: 'Vorschlag und Reaktion',
    coreMeaning: 'Es geht bei mir nicht.',
    targetExplanation: 'On refuse parce que ce n’est pas possible.',
    communicativeFunction: 'einen Vorschlag ablehnen',
    modelUtterance: 'Désolé, je ne peux pas, j’ai un cours de piano.',
    lexicalType: 'sprechakt',
    semantisationMethod: 'Situation mit klarem Bedarf inszenieren',
    repertoire: 'kern',
    situation: 'Eine Einladung kommt, aber der Terminkalender ist voll.',
    pronunciationHint: 'Mündlich fällt „ne“ meist weg: „je peux pas“.',
    prosodyNote: 'Bedauernder Tonfall; ohne ihn wirkt die Absage schroff.',
    ipa: '[ʒə nə pø pa]',
    morphology: 'pouvoir: je peux, tu peux, il/elle peut',
    valency: 'pouvoir + Infinitiv',
    sentenceFrame: 'Je ne peux pas, ______ (Begründung).',
    collocations: 'je ne peux pas venir / rester / sortir',
    wordFamily: 'pouvoir – possible',
    register: 'neutral bis mündlich',
    example: 'Je ne peux pas venir samedi.',
    nonExample: 'Je ne veux pas. – das ist kein Terminproblem, sondern eine Zurückweisung.',
    contrastExample: 'Je ne veux pas. – Ablehnung aus Unlust.',
    confusionRisk: 'Verwechslung von „pouvoir“ (können) und „vouloir“ (wollen).',
    checkTemplateId: 'welche-reaktion',
    ccqs: [
      createConceptCheck({
        question: 'La personne ne veut pas ou elle n’a pas le temps ?',
        expectedAnswer: 'Elle n’a pas le temps.',
        options: ['Elle ne veut pas.', 'Elle n’a pas le temps.'],
        feature: 'modalitaet',
        format: 'a-b',
        target: 'meaning',
        misconception: '„pouvoir“ wird wie „vouloir“ verstanden.',
        alternativeClarification: '„Je ne veux pas“ danebenstellen und beide Situationen zuordnen lassen.',
        language: 'fr',
      }),
    ],
    translation: 'Ich kann nicht.',
    simplifiedExplanation: 'Man sagt höflich ab und nennt einen Grund.',
    extraHint: 'Immer mit Begründung anbieten – sonst wirkt die Absage unhöflich.',
    communicativeTask: 'Sagt zu einem Vorschlag höflich ab und nennt einen Grund.',
  },
  {
    expression: 'jouer à / jouer de',
    learningGoal: 'productive',
    imageability: 'mittel',
    inferenceSuitability: 'geeignet',
    transferRisk: 'hoch',
    coreMeaning: 'etwas spielen – Sport und Spiel mit „à“, Instrumente mit „de“',
    targetExplanation: 'jouer à : sport ou jeu · jouer de : instrument de musique',
    targetPrompt: 'Comparez les phrases.',
    communicativeFunction: 'sagen, was man spielt',
    modelUtterance: 'Le mercredi, je joue au badminton et le soir, je joue de la guitare.',
    lexicalType: 'kollokation',
    semantisationMethod: 'Belege vergleichen und sortieren lassen',
    repertoire: 'kern',
    situation: 'In der Klasse wird gesammelt, was alle in ihrer Freizeit spielen – Sport und Musik gemischt.',
    pronunciationHint: '„jouer“ mit stimmhaftem [ʒ]; „aux“ vor Vokal gebunden: aux_échecs.',
    ipa: '[ʒwe]',
    morphology: 'jouer à + le → au, à + les → aux; jouer de + le → du, de + la → de la',
    valency: 'jouer à + Sport oder Spiel; jouer de + Instrument',
    sentenceFrame: 'jouer ______ (au / aux / du / de la) + ______',
    collocations: 'jouer au foot, jouer aux cartes, jouer du violon, jouer de la batterie',
    wordFamily: 'un jeu – un joueur – une joueuse',
    register: 'neutral',
    example: 'Ma sœur joue du piano depuis trois ans.',
    nonExample: 'jouer le tennis – die Verschmelzung mit „à“ fehlt.',
    contrastExample: 'faire du skate – bei vielen Sportarten ohne Ball steht „faire de“.',
    confusionRisk: 'Im Deutschen steht in beiden Fällen nur „spielen“; „à“ und „de“ werden deshalb häufig vertauscht.',
    checkTemplateId: 'welcher-ausdruck-fehlt',
    ccqs: [
      createConceptCheck({
        question: 'Le tennis, c’est un sport ou un instrument ?',
        expectedAnswer: 'Un sport.',
        options: ['Un sport', 'Un instrument'],
        feature: 'begriffsgrenze',
        format: 'a-b',
        target: 'meaning',
        misconception: 'Die Unterscheidung Sport/Instrument wird nicht als Bedingung erkannt.',
        alternativeClarification: 'Zwei Spalten anlegen und je zwei Beispiele einordnen lassen.',
        language: 'fr',
      }),
      createConceptCheck({
        question: 'Après « jouer », pour la guitare : à ou de ?',
        expectedAnswer: 'de',
        options: ['à', 'de'],
        feature: 'kernbedeutung',
        format: 'a-b',
        target: 'meaning',
        language: 'fr',
      }),
    ],
    translation: 'spielen',
    extraHint: 'Zuerst die beiden Gruppen sichern, dann erst weitere Aktivitäten sammeln.',
    communicativeTask: 'Erzählt zu zweit, was ihr spielt – mindestens einmal mit „à“ und einmal mit „de“.',
    // Die Korpusminiatur ist bewusst nur für diese eine Einheit eingeschaltet.
    stepOverrides: { korpusminiatur: true },
    corpus: createCorpusMiniature({
      enabled: true,
      title: 'jouer à oder jouer de?',
      guidingQuestion: 'Was steht nach jouer, wenn von einem Sport oder einem Instrument gesprochen wird?',
      focus: 'pattern',
      examples: [
        createCorpusExample({
          text: 'Le samedi, nous jouons au tennis avec mon frère.',
          highlight: 'au tennis',
          category: 'Sport/Spiel',
          teacherNote: 'Erster klarer Fall: Sportart mit Artikel „le“ → au.',
        }),
        createCorpusExample({
          text: 'À la récréation, ils jouent aux échecs dans la bibliothèque.',
          highlight: 'aux échecs',
          category: 'Sport/Spiel',
          teacherNote: 'Plural: à + les → aux; hier zusätzlich die Bindung aux_échecs hörbar machen.',
        }),
        createCorpusExample({
          text: 'Ma cousine joue du piano tous les jours.',
          highlight: 'du piano',
          category: 'Instrument',
          teacherNote: 'Gegenbeispiel zur ersten Gruppe – bewusst direkt nach den Sportbelegen zeigen.',
        }),
        createCorpusExample({
          text: 'Depuis septembre, je joue de la guitare dans un groupe.',
          highlight: 'de la guitare',
          category: 'Instrument',
          teacherNote: 'Feminines Instrument: de la, keine Verschmelzung.',
        }),
        createCorpusExample({
          text: 'Le mercredi après-midi, elles jouent au badminton au gymnase.',
          highlight: 'au badminton',
          category: 'Sport/Spiel',
          teacherNote: 'Zweiter Sportbeleg zur Absicherung, bevor sortiert wird.',
        }),
        createCorpusExample({
          text: 'Mon voisin joue de la batterie le week-end.',
          highlight: 'de la batterie',
          category: 'Instrument',
          teacherNote: 'Letzter Beleg – erst danach die Regel gemeinsam formulieren lassen.',
        }),
      ],
      discoveryPrompt: 'Sortiert die Belege in zwei Gruppen: Was gehört zusammen? Woran erkennt ihr die Gruppen?',
      ruleOrFinding: 'jouer à + Sport/Spiel · jouer de + Instrument',
      transferPrompt: 'Bildet je einen eigenen Satz mit beiden Mustern – einmal mit „à“, einmal mit „de“.',
      provenance: 'teacher-created',
      sourceNote:
        'Selbst formulierte Beispielsätze für den Unterricht – keine authentischen Korpusbelege.',
    }),
  },
  {
    expression: 'On se retrouve à…',
    learningGoal: 'productive',
    imageability: 'gering',
    inferenceSuitability: 'bedingt',
    transferRisk: 'mittel',
    coreMeaning: 'Wir treffen uns um / an …',
    communicativeFunction: 'Zeit und Treffpunkt vereinbaren',
    modelUtterance: 'On se retrouve à 15 heures devant le cinéma ?',
    lexicalType: 'kollokation',
    semantisationMethod: 'Satzrahmen an der Tafel',
    repertoire: 'kern',
    situation: 'Die Aktivität steht fest, jetzt fehlen noch Uhrzeit und Treffpunkt.',
    pronunciationHint: 'Liaison in „On se retrouve à“ nicht übertreiben; „à“ bleibt kurz.',
    ipa: '[ɔ̃ sə ʁə.tʁuv a]',
    morphology: 'se retrouver, reflexiv: on se retrouve, nous nous retrouvons',
    valency: 'se retrouver à + Uhrzeit / devant + Ort',
    sentenceFrame: 'On se retrouve à ______ devant ______ ?',
    collocations: 'se retrouver à midi, devant l’école, à la gare',
    wordFamily: 'retrouver – une retrouvaille',
    register: 'mündlich, verabredend',
    example: 'On se retrouve à 14 h devant la médiathèque.',
    nonExample: 'On se trouve à 15 heures. – „se trouver“ heißt „sich befinden“.',
    contrastExample: 'On se voit demain. – allgemeiner, ohne festen Treffpunkt.',
    confusionRisk: 'trouver / se trouver / retrouver werden leicht verwechselt.',
    checkTemplateId: 'welcher-ausdruck-fehlt',
    translation: 'Wir treffen uns um …',
    communicativeTask: 'Einigt euch zu zweit auf Uhrzeit und Treffpunkt.',
  },
];

export function createDemoSequence(): Sequence {
  const lexemes = SEEDS.map((seed) => createLexeme(seed));
  return createSequence({
    title: 'Freizeit verabreden',
    targetLanguage: 'fr',
    learningGroup: 'Klasse 7 · Französisch, 2. Lernjahr',
    learnerLevel: 'anfaenger',
    inferenceMode: 'optional',
    topic: 'Am Wochenende gemeinsam etwas unternehmen',
    canDoGoal:
      'Die Lernenden können eine gemeinsame Aktivität vorschlagen, auf Vorschläge reagieren und sich auf Zeit und Ort einigen.',
    taskType: 'rollenspiel',
    targetTask:
      'Zu zweit einen gemeinsamen Samstagnachmittag verabreden: vorschlagen, zustimmen oder ablehnen, Zeit und Treffpunkt festlegen.',
    teacherNote:
      'Regieentscheidung für diese Sequenz: Klangbild vor dem Schriftbild anbieten und die Bedeutung vorher klären. Bei „Pourquoi pas !“ nicht raten lassen – die wörtliche Lesart führt in die Irre.',
    lexemes,
  });
}

export const DEMO_TITLE = 'Freizeit verabreden';
