/**
 * Mitgelieferte Beispielsequenz (Französisch).
 *
 * Sie ist vollständig ausgefüllt, damit der Unterrichtsmodus ohne
 * Vorbereitungsaufwand erprobt werden kann. Medien sind bewusst nicht
 * enthalten – die App lädt keine Dateien aus dem Netz.
 */
import type { Lexeme, Sequence } from './model';
import { createLexeme, createSequence } from './schema';

type LexemeSeed = Partial<Lexeme> & Pick<Lexeme, 'expression' | 'coreMeaning'>;

const SEEDS: LexemeSeed[] = [
  {
    expression: 'Ça te dit de… ?',
    coreMeaning: 'Hast du Lust, etwas zu tun?',
    communicativeFunction: 'einen Vorschlag machen',
    modelUtterance: "Ça te dit d'aller au cinéma samedi ?",
    lexicalType: 'sprechakt',
    semantisationMethod: 'Mini-Dialog mit Reaktion',
    repertoire: 'kern',
    situation: 'Zwei Jugendliche schreiben sich am Freitagnachmittag. Eine Person möchte etwas gemeinsam unternehmen.',
    pronunciationHint: 'Bindung zwischen „Ça“ und „te“ nicht trennen; der Satz steigt am Ende an.',
    prosodyNote: 'Fragemelodie steigend; „de“ wird zu „d’“ vor Vokal.',
    ipa: '[sa tə di də]',
    morphology: 'unveränderlicher Chunk; „te“ nur beim Duzen, sonst „Ça vous dit de… ?“',
    valency: 'Ça te dit de + Infinitiv',
    sentenceFrame: 'Ça te dit de ______ ?',
    collocations: "Ça te dit d'aller… / de venir… / de faire…",
    wordFamily: 'dire – ça me dit – ça ne me dit rien',
    register: 'mündlich, vertraut (Duzen)',
    culturalNote: 'Unter Jugendlichen die übliche Form des Vorschlags; im Brief oder gegenüber Erwachsenen zu informell.',
    example: "Ça te dit de venir avec nous au parc ?",
    nonExample: 'Ça te dit de remplir ce formulaire ? – Ein Vorschlag ohne Freizeitcharakter wirkt seltsam.',
    contrastExample: 'Vous voulez venir avec nous ? – derselbe Zweck, formeller Register.',
    confusionRisk: '„Ça te dit quelque chose ?“ heißt „Sagt dir das etwas?“ – andere Bedeutung.',
    checkTemplateId: 'sprechhandlung',
    translation: 'Hast du Lust, …?',
    simplifiedExplanation: 'Man fragt: Willst du mitmachen?',
    extraHint: 'Chunk als Ganzes lernen, nicht Wort für Wort übersetzen.',
    extensionTask: 'Formuliert denselben Vorschlag höflich mit „Ça vous dit de… ?“.',
    communicativeTask: 'Schlagt eurer Partnerin oder eurem Partner eine Aktivität für Samstag vor.',
  },
  {
    expression: 'Pourquoi pas !',
    coreMeaning: 'Einverstanden, gute Idee.',
    communicativeFunction: 'einem Vorschlag zustimmen',
    modelUtterance: '— Ça te dit d’aller à la piscine ? — Pourquoi pas !',
    lexicalType: 'sprechakt',
    semantisationMethod: 'Mini-Dialog mit Reaktion',
    repertoire: 'kern',
    situation: 'Auf einen Vorschlag folgt eine freundliche, offene Zustimmung.',
    pronunciationHint: 'Kein Fragezeichen: fallende Melodie, sonst klingt es nach echter Rückfrage.',
    prosodyNote: 'Betonung auf „pas“; fallende Intonation.',
    ipa: '[puʁ.kwa pa]',
    morphology: 'feste Wendung, unveränderlich',
    sentenceFrame: '— Vorschlag — Pourquoi pas !',
    register: 'mündlich, freundlich',
    example: '— On fait du vélo ? — Pourquoi pas !',
    nonExample: 'Pourquoi pas ? mit Fragemelodie ist keine Zustimmung, sondern eine Rückfrage.',
    contrastExample: 'Bonne idée ! – deutlichere Begeisterung.',
    confusionRisk: 'Wörtlich „Warum nicht?“ – im Deutschen klingt das zögernd, im Französischen ist es zustimmend.',
    checkTemplateId: 'sprechhandlung',
    translation: 'Warum nicht! / Gerne!',
    extraHint: 'Intonation mitsprechen lassen – sie trägt hier die Bedeutung.',
    communicativeTask: 'Reagiert auf drei Vorschläge eurer Partnerin oder eures Partners.',
  },
  {
    expression: 'Je préfère…',
    coreMeaning: 'Ich möchte lieber etwas anderes.',
    communicativeFunction: 'eine Präferenz ausdrücken',
    modelUtterance: 'Je préfère faire du skate.',
    lexicalType: 'kollokation',
    semantisationMethod: 'Satzrahmen an der Tafel',
    repertoire: 'kern',
    situation: 'Zwei Vorschläge liegen auf dem Tisch; eine Person wählt einen davon aus.',
    pronunciationHint: 'Offenes è in „préfère“ – anders als in „préférer“.',
    prosodyNote: 'Akzentwechsel: je préfère, aber nous préférons.',
    ipa: '[ʒə pʁe.fɛʁ]',
    morphology: 'préférer, Stammwechsel é → è: je préfère, tu préfères, nous préférons',
    valency: 'préférer + Infinitiv oder + Nomen',
    sentenceFrame: 'Je préfère ______ .',
    collocations: 'je préfère aller… / faire… / rester…',
    wordFamily: 'la préférence – préféré(e)',
    register: 'neutral',
    example: 'Je préfère rester à la maison.',
    nonExample: 'Je préfère que tu viens. – hier wäre der Subjonctif nötig.',
    contrastExample: 'Je veux faire du skate. – Wunsch statt Auswahl.',
    confusionRisk: 'Nicht mit „Je préférerais“ (höflicher Konditional) verwechseln.',
    checkTemplateId: 'welche-situation',
    translation: 'Ich mag lieber …',
    multilingualComparison: 'engl. I prefer to … – gleiche Struktur mit Infinitiv.',
    communicativeTask: 'Lehnt einen Vorschlag freundlich ab und nennt eine Alternative.',
  },
  {
    expression: 'aller au cinéma',
    coreMeaning: 'ins Kino gehen',
    communicativeFunction: 'eine Aktivität benennen',
    modelUtterance: 'On peut aller au cinéma dimanche après-midi.',
    lexicalType: 'kollokation',
    semantisationMethod: 'Bausteinmuster mit Varianten',
    repertoire: 'kern',
    situation: 'Ein Kinoprogramm hängt aus; die Gruppe überlegt, was sie unternehmen kann.',
    pronunciationHint: 'Liaison: „aller_au“ wird gebunden gesprochen.',
    ipa: '[a.le o si.ne.ma]',
    morphology: 'aller à + le → au; à la piscine, à l’opéra, aux Halles',
    valency: 'aller à + Ort',
    sentenceFrame: 'aller ______ (au / à la / à l’)',
    collocations: 'aller au cinéma, aller au parc, aller à la piscine',
    wordFamily: 'le cinéma – une séance – un film',
    register: 'neutral',
    example: 'Samedi soir, on va au cinéma.',
    nonExample: 'aller à le cinéma – die Verschmelzung fehlt.',
    contrastExample: 'aller à la piscine – gleiches Muster, anderes Genus.',
    confusionRisk: 'Kontraktion au/à la wird häufig übergeneralisiert.',
    checkTemplateId: 'welcher-ausdruck-fehlt',
    translation: 'ins Kino gehen',
    communicativeTask: 'Nennt drei Orte, die ihr am Wochenende besuchen könnt.',
  },
  {
    expression: 'faire du skate',
    coreMeaning: 'Skateboard fahren',
    communicativeFunction: 'eine Freizeitaktivität benennen',
    modelUtterance: 'Le samedi, je fais du skate au parc.',
    lexicalType: 'handlung',
    semantisationMethod: 'Pantomime durch die Lehrkraft',
    repertoire: 'stuetze',
    situation: 'Im Park üben Jugendliche mit ihren Skateboards.',
    pronunciationHint: '„skate“ wird französisch ausgesprochen: [skɛt].',
    ipa: '[fɛʁ dy skɛt]',
    morphology: 'faire du / de la / de l’ + Sportart',
    valency: 'faire de + Aktivität',
    sentenceFrame: 'faire ______ (du / de la / de l’)',
    collocations: 'faire du vélo, faire de la danse, faire de l’escalade',
    wordFamily: 'un skateur – une planche',
    register: 'mündlich, jugendsprachlich verbreitet',
    example: 'Mon frère fait du skate tous les mercredis.',
    nonExample: 'jouer au skate – im Französischen nur bei Ballspielen: jouer au foot.',
    contrastExample: 'jouer au foot – anderes Muster für Mannschaftssport.',
    confusionRisk: 'faire de vs. jouer à wird oft vertauscht.',
    checkTemplateId: 'welches-bild',
    translation: 'skaten',
    extensionTask: 'Sammelt fünf weitere Aktivitäten mit „faire du / de la“.',
    communicativeTask: 'Erzählt, welche Aktivität ihr am Wochenende macht.',
  },
  {
    expression: 'Je ne peux pas.',
    coreMeaning: 'Es geht bei mir nicht.',
    communicativeFunction: 'einen Vorschlag ablehnen',
    modelUtterance: 'Désolé, je ne peux pas, j’ai un cours de piano.',
    lexicalType: 'sprechakt',
    semantisationMethod: 'Situation mit klarem Bedarf inszenieren',
    repertoire: 'kern',
    situation: 'Eine Einladung kommt, aber der Terminkalender ist voll.',
    pronunciationHint: 'Mündlich fällt „ne“ meist weg: „je peux pas“.',
    prosodyNote: 'Bedauernder Tonfall; ohne ihn wirkt die Absage schroff.',
    ipa: '[ʒə nə pø pa]',
    morphology: 'pouvoir: je peux, tu peux, il/elle peut',
    valency: 'pouvoir + Infinitiv',
    sentenceFrame: 'Je ne peux pas, ______ (Begründung).',
    collocations: 'je ne peux pas venir / rester / sortir',
    wordFamily: 'pouvoir – possible',
    register: 'neutral bis mündlich',
    example: 'Je ne peux pas venir samedi.',
    nonExample: 'Je ne veux pas. – das ist kein Terminproblem, sondern eine Zurückweisung.',
    contrastExample: 'Je ne veux pas. – Ablehnung aus Unlust.',
    confusionRisk: 'Verwechslung von „pouvoir“ (können) und „vouloir“ (wollen).',
    checkTemplateId: 'welche-reaktion',
    translation: 'Ich kann nicht.',
    simplifiedExplanation: 'Man sagt höflich ab und nennt einen Grund.',
    extraHint: 'Immer mit Begründung anbieten – sonst wirkt die Absage unhöflich.',
    communicativeTask: 'Sagt zu einem Vorschlag höflich ab und nennt einen Grund.',
  },
  {
    expression: 'On se retrouve à…',
    coreMeaning: 'Wir treffen uns um / an …',
    communicativeFunction: 'Zeit und Treffpunkt vereinbaren',
    modelUtterance: 'On se retrouve à 15 heures devant le cinéma ?',
    lexicalType: 'kollokation',
    semantisationMethod: 'Satzrahmen an der Tafel',
    repertoire: 'kern',
    situation: 'Die Aktivität steht fest, jetzt fehlen noch Uhrzeit und Treffpunkt.',
    pronunciationHint: 'Liaison in „On se retrouve à“ nicht übertreiben; „à“ bleibt kurz.',
    ipa: '[ɔ̃ sə ʁə.tʁuv a]',
    morphology: 'se retrouver, reflexiv: on se retrouve, nous nous retrouvons',
    valency: 'se retrouver à + Uhrzeit / devant + Ort',
    sentenceFrame: 'On se retrouve à ______ devant ______ ?',
    collocations: 'se retrouver à midi, devant l’école, à la gare',
    wordFamily: 'retrouver – une retrouvaille',
    register: 'mündlich, verabredend',
    example: 'On se retrouve à 14 h devant la médiathèque.',
    nonExample: 'On se trouve à 15 heures. – „se trouver“ heißt „sich befinden“.',
    contrastExample: 'On se voit demain. – allgemeiner, ohne festen Treffpunkt.',
    confusionRisk: 'trouver / se trouver / retrouver werden leicht verwechselt.',
    checkTemplateId: 'welcher-ausdruck-fehlt',
    translation: 'Wir treffen uns um …',
    communicativeTask: 'Einigt euch zu zweit auf Uhrzeit und Treffpunkt.',
  },
];

export function createDemoSequence(): Sequence {
  const lexemes = SEEDS.map((seed) => createLexeme(seed));
  return createSequence({
    title: 'Freizeit verabreden',
    targetLanguage: 'fr',
    learningGroup: 'Klasse 7 · Französisch, 2. Lernjahr',
    topic: 'Am Wochenende gemeinsam etwas unternehmen',
    canDoGoal:
      'Die Lernenden können eine gemeinsame Aktivität vorschlagen, auf Vorschläge reagieren und sich auf Zeit und Ort einigen.',
    teacherNote:
      'Chunks zuerst hörend anbieten, Schriftbild erst nach der Bedeutungsklärung. Übersetzung nur bei „Ça te dit de… ?“ als Absicherung einsetzen.',
    lexemes,
  });
}

export const DEMO_TITLE = 'Freizeit verabreden';
